// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };

// module.exports = sidebars;


module.exports = {
  mySidebar: [
    'crazyJs',
    {
      type: 'category',
      label: 'HTML+CSS学习',
      items: [
        'HTML+CSS/html',
        'HTML+CSS/css',
        'HTML+CSS/h5c3',
        'HTML+CSS/dom',
        'HTML+CSS/bom',
        'HTML+CSS/mobile',
        'HTML+CSS/flexbox',
        'HTML+CSS/grid',
      ]
    },
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        'JavaScript/regexp',
      ]
    }

    // 'a'
    // ''
  ],

};

// module.exports = {
//   myAutogeneratedSidebar: [
//     {
//       type: 'autogenerated',
//       dirName: '.', // '.' means the current docs folder
//     },
//   ],
// };